language: java
arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
script: 
  - export pwd=$PWD && echo $PWD
  - export BUILD_TAG=7_`date +%Y%m%d`
  - docker build . -f ./extras/debian.Dockerfile -t toyangdon/gluster-exporter:$BUILD_TAG
  - docker push toyangdon/gluster-exporter:$BUILD_TAG
